function res = is_ok(char)
    res =	strcmp(char, 'Yes')     || ...
        	strcmp(char, 'YES')     || ...
            strcmp(char, 'Y')       || ...
            strcmp(char, 'yes')     || ... 
            strcmp(char, 'y')       || ... 
            strcmp(char, 'ok')      || ...
            strcmp(char, 'OK')      || ... 
            strcmp(char, 'Ok')      || ... 
            strcmp(char, 'k')       || ... 
            strcmp(char, 'K')       || ... 
            strcmp(char, 'Yea') 	|| ... 
            strcmp(char, 'YEA')     || ... 
            strcmp(char, 'yea')     || ... 
            strcmp(char, 'fine')    || ... 
            strcmp(char, 'FINE')	|| ... 
            strcmp(char, 'okay')	|| ... 
            strcmp(char, 'Okay')	|| ... 
            strcmp(char, 'OKAY')	|| ... 
            strcmp(char, 'good')	|| ... 
            strcmp(char, 'GOOD')	|| ... 
            strcmp(char, 'Good')	|| ... 
            strcmp(char, 'Aye')     || ... 
            strcmp(char, 'aye')     || ... 
            strcmp(char, 'AYE')     || ... 
            strcmp(char, 'Yep')     || ... 
            strcmp(char, 'yep')     || ... 
            strcmp(char, 'YEP')     || ... 
            strcmp(char, 'y');
end

